-- Scoutly App DB migration: durable Agentic queue and results.
create table if not exists public.agent_runs (
  id uuid primary key default gen_random_uuid(),
  user_uid text not null,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  objective text not null,
  current_region_name text not null default 'São Paulo - SP',
  status text not null default 'queued' check (status in ('queued','planning','searching','qualifying','saving','completed','failed','cancelled')),
  stage text not null default 'planning',
  target_count integer not null default 25 check (target_count between 1 and 500),
  found_count integer not null default 0,
  processed_count integer not null default 0,
  qualified_count integer not null default 0,
  saved_count integer not null default 0,
  progress integer not null default 0 check (progress between 0 and 100),
  priority smallint not null default 0,
  current_message text not null default 'Na fila',
  plan jsonb not null default '{}'::jsonb,
  result_summary jsonb not null default '{}'::jsonb,
  error text,
  attempts integer not null default 0,
  worker_id text,
  lock_token uuid,
  locked_until timestamptz,
  next_attempt_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agent_run_steps (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.agent_runs(id) on delete cascade,
  step_key text not null,
  label text not null,
  status text not null default 'pending' check (status in ('pending','running','completed','failed','skipped')),
  attempt integer not null default 0,
  input jsonb not null default '{}'::jsonb,
  output jsonb not null default '{}'::jsonb,
  error text,
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(run_id, step_key)
);

create table if not exists public.agent_run_leads (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.agent_runs(id) on delete cascade,
  business_id text not null,
  status text not null default 'candidate' check (status in ('candidate','qualified','rejected','saved')),
  initial_score numeric(7,2) not null default 0,
  score numeric(7,2) not null default 0,
  reasons jsonb not null default '[]'::jsonb,
  business_snapshot jsonb not null,
  enrichment jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(run_id, business_id)
);

create table if not exists public.agent_run_events (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.agent_runs(id) on delete cascade,
  level text not null default 'info' check (level in ('debug','info','warning','error','success')),
  event_type text not null,
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_agent_runs_user_created on public.agent_runs(user_uid, created_at desc);
create index if not exists idx_agent_runs_queue on public.agent_runs(status, next_attempt_at, priority desc, created_at)
  where status in ('queued','planning','searching','qualifying','saving');
create index if not exists idx_agent_runs_lock on public.agent_runs(locked_until)
  where status in ('queued','planning','searching','qualifying','saving');
create index if not exists idx_agent_run_steps_run on public.agent_run_steps(run_id, id);
create index if not exists idx_agent_run_leads_run_status_score on public.agent_run_leads(run_id, status, score desc, initial_score desc);
create index if not exists idx_agent_run_events_run_created on public.agent_run_events(run_id, created_at desc);

alter table public.user_leads add column if not exists source_agent_run_id uuid references public.agent_runs(id) on delete set null;

alter table public.agent_runs enable row level security;
alter table public.agent_run_steps enable row level security;
alter table public.agent_run_leads enable row level security;
alter table public.agent_run_events enable row level security;

create or replace function public.claim_scoutly_agent_run(p_worker_id text, p_lock_seconds integer default 45)
returns setof public.agent_runs
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with candidate as (
    select r.id
    from public.agent_runs r
    where r.status in ('queued','planning','searching','qualifying','saving')
      and r.next_attempt_at <= now()
      and (r.locked_until is null or r.locked_until < now())
    order by r.priority desc, r.created_at asc
    for update skip locked
    limit 1
  )
  update public.agent_runs r
  set
    status = case when r.status = 'queued' then 'planning' else r.status end,
    stage = case when r.status = 'queued' then 'planning' else r.stage end,
    started_at = coalesce(r.started_at, now()),
    worker_id = p_worker_id,
    lock_token = gen_random_uuid(),
    locked_until = now() + make_interval(secs => greatest(15, least(coalesce(p_lock_seconds, 45), 180))),
    updated_at = now()
  from candidate c
  where r.id = c.id
  returning r.*;
end;
$$;
