-- Scoutly Internal backoffice: staff access, support tickets, messages and audit trail.

create table if not exists public.internal_staff (
  firebase_uid text primary key,
  email text,
  display_name text,
  role text not null default 'support'
    check (role in ('admin', 'support', 'viewer')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists internal_staff_email_unique
  on public.internal_staff (lower(email))
  where email is not null;

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  user_uid text,
  requester_email text,
  requester_name text,
  subject text not null,
  category text not null default 'OTHER'
    check (category in ('BILLING','SEARCH','ACCOUNT','AI','PIPELINE','DATA','BUG','OTHER')),
  priority text not null default 'NORMAL'
    check (priority in ('LOW','NORMAL','HIGH','URGENT')),
  status text not null default 'OPEN'
    check (status in ('OPEN','IN_PROGRESS','WAITING_CUSTOMER','WAITING_INTERNAL','RESOLVED','CLOSED')),
  assigned_to text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists support_tickets_status_idx
  on public.support_tickets (status, updated_at desc);

create index if not exists support_tickets_user_uid_idx
  on public.support_tickets (user_uid, updated_at desc);

create index if not exists support_tickets_assigned_to_idx
  on public.support_tickets (assigned_to, updated_at desc);

create table if not exists public.support_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets(id) on delete cascade,
  author_type text not null default 'staff'
    check (author_type in ('customer','staff','system')),
  author_uid text,
  author_name text,
  body text not null,
  is_internal boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists support_messages_ticket_idx
  on public.support_messages (ticket_id, created_at asc);

create table if not exists public.internal_audit_logs (
  id bigint generated by default as identity primary key,
  actor_uid text,
  actor_email text,
  action text not null,
  target_type text,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists internal_audit_logs_created_idx
  on public.internal_audit_logs (created_at desc);

create or replace function public.scoutly_touch_internal_row()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists internal_staff_touch_updated_at on public.internal_staff;
create trigger internal_staff_touch_updated_at
before update on public.internal_staff
for each row execute function public.scoutly_touch_internal_row();

drop trigger if exists support_tickets_touch_updated_at on public.support_tickets;
create trigger support_tickets_touch_updated_at
before update on public.support_tickets
for each row execute function public.scoutly_touch_internal_row();
