-- Scoutly Internal secure access gate.
-- Runtime secrets/allowlist values are seeded out-of-band and are intentionally
-- not committed to source control.

create table if not exists public.internal_access_allowlist (
  email text primary key,
  role text not null default 'admin'
    check (role in ('admin', 'support', 'viewer')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.internal_security_config (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.internal_gate_sessions (
  token_hash text primary key,
  stage text not null
    check (stage in ('code_verified', 'authorized')),
  firebase_uid text,
  email text,
  role text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists internal_gate_sessions_expires_idx
  on public.internal_gate_sessions (expires_at);

create table if not exists public.internal_access_attempts (
  id bigint generated by default as identity primary key,
  fingerprint_hash text not null,
  success boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists internal_access_attempts_lookup_idx
  on public.internal_access_attempts (fingerprint_hash, created_at desc);
