-- Scoutly Support Center v2: triage tags and optional screenshot attachments.

alter table public.support_tickets
  add column if not exists tags text[] not null default '{}'::text[];

create table if not exists public.support_attachments (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets(id) on delete cascade,
  uploaded_by_uid text,
  file_name text not null,
  mime_type text not null
    check (mime_type in ('image/png', 'image/jpeg', 'image/webp')),
  file_size bigint not null
    check (file_size > 0 and file_size <= 1600000),
  data_url text not null
    check (char_length(data_url) <= 2200000),
  created_at timestamptz not null default now()
);

create index if not exists support_attachments_ticket_idx
  on public.support_attachments (ticket_id, created_at asc);

-- Attachments are only read/written through authenticated Scoutly server actions.
-- Keep the table inaccessible to browser Data API roles.
alter table public.support_attachments enable row level security;
revoke all on table public.support_attachments from anon, authenticated;
