-- Scoutly freemium credit ledger.
-- All resets are derived from PostgreSQL now() in UTC; clients never provide dates, plan or balances.

create table if not exists public.scoutly_usage_events (
  id bigint generated by default as identity primary key,
  user_uid text not null,
  feature text not null check (feature in ('business_unlock', 'ai_conversation')),
  resource_id text,
  plan text not null,
  created_at timestamptz not null default now()
);

create index if not exists scoutly_usage_events_user_feature_created_idx
  on public.scoutly_usage_events (user_uid, feature, created_at desc);

create unique index if not exists scoutly_business_unlock_once_idx
  on public.scoutly_usage_events (user_uid, resource_id)
  where feature = 'business_unlock' and resource_id is not null;

alter table public.scoutly_usage_events enable row level security;
revoke all on public.scoutly_usage_events from anon, authenticated;
grant select, insert on public.scoutly_usage_events to service_role;
grant usage, select on sequence public.scoutly_usage_events_id_seq to service_role;

create or replace function public.scoutly_effective_plan(p_user_uid text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plan text;
  v_status text;
  v_end timestamptz;
begin
  select lower(coalesce(plan, 'free')), lower(coalesce(status, 'active')), current_period_end
    into v_plan, v_status, v_end
  from public.subscriptions
  where user_uid = p_user_uid
  limit 1;

  if not found then return 'free'; end if;

  if v_plan in ('go','pro','agency') and v_status in ('active','trialing','past_due') then
    return v_plan;
  end if;

  -- Legacy 7-day trials keep their entitlement only until their persisted end.
  if v_plan = 'trial' and v_status = 'trialing' and v_end is not null and v_end > now() then
    return 'trial';
  end if;

  return 'free';
end;
$$;

create or replace function public.scoutly_credit_status(p_user_uid text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plan text := public.scoutly_effective_plan(p_user_uid);
  v_day_start timestamptz := date_trunc('day', now() at time zone 'UTC') at time zone 'UTC';
  v_day_end timestamptz := (date_trunc('day', now() at time zone 'UTC') + interval '1 day') at time zone 'UTC';
  v_month_start timestamptz := date_trunc('month', now() at time zone 'UTC') at time zone 'UTC';
  v_month_end timestamptz := (date_trunc('month', now() at time zone 'UTC') + interval '1 month') at time zone 'UTC';
  v_period_start timestamptz;
  v_period_end timestamptz;
  v_daily_limit integer;
  v_monthly_limit integer;
  v_ai_daily_limit integer;
  v_daily_used integer := 0;
  v_monthly_used integer := 0;
  v_ai_daily_used integer := 0;
begin
  if v_plan = 'free' then
    v_daily_limit := 5;
    v_monthly_limit := 25;
    v_ai_daily_limit := 0;
    v_period_start := v_month_start;
    v_period_end := v_month_end;
  elsif v_plan = 'go' then
    v_daily_limit := null;
    v_monthly_limit := 80;
    v_ai_daily_limit := 10;
    select coalesce(current_period_start, v_month_start), coalesce(current_period_end, v_month_end)
      into v_period_start, v_period_end
    from public.subscriptions where user_uid = p_user_uid limit 1;
    if v_period_start is null or v_period_end is null or v_period_end <= v_period_start then
      v_period_start := v_month_start;
      v_period_end := v_month_end;
    end if;
  else
    v_daily_limit := null;
    v_monthly_limit := null;
    v_ai_daily_limit := null;
    v_period_start := v_month_start;
    v_period_end := v_month_end;
  end if;

  select count(*)::int into v_daily_used
  from public.scoutly_usage_events
  where user_uid = p_user_uid and feature = 'business_unlock' and created_at >= v_day_start and created_at < v_day_end;

  select count(*)::int into v_monthly_used
  from public.scoutly_usage_events
  where user_uid = p_user_uid and feature = 'business_unlock' and created_at >= v_period_start and created_at < v_period_end;

  select count(*)::int into v_ai_daily_used
  from public.scoutly_usage_events
  where user_uid = p_user_uid and feature = 'ai_conversation' and created_at >= v_day_start and created_at < v_day_end;

  return jsonb_build_object(
    'plan', v_plan,
    'dailyLimit', v_daily_limit,
    'dailyUsed', v_daily_used,
    'dailyRemaining', case when v_daily_limit is null then null else greatest(v_daily_limit - v_daily_used, 0) end,
    'monthlyLimit', v_monthly_limit,
    'monthlyUsed', v_monthly_used,
    'monthlyRemaining', case when v_monthly_limit is null then null else greatest(v_monthly_limit - v_monthly_used, 0) end,
    'aiDailyLimit', v_ai_daily_limit,
    'aiDailyUsed', v_ai_daily_used,
    'aiDailyRemaining', case when v_ai_daily_limit is null then null else greatest(v_ai_daily_limit - v_ai_daily_used, 0) end,
    'dailyResetAt', v_day_end,
    'monthlyResetAt', v_period_end,
    'recommendationsAccess', v_plan in ('pro','agency','trial'),
    'aiAccess', v_plan in ('go','pro','agency','trial')
  );
end;
$$;

create or replace function public.scoutly_consume_business_credit(p_user_uid text, p_business_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status jsonb;
  v_plan text;
  v_exists boolean;
  v_allowed boolean := false;
begin
  if coalesce(trim(p_user_uid),'') = '' or coalesce(trim(p_business_id),'') = '' then
    raise exception 'invalid credit request';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_user_uid, 7719));

  select exists(
    select 1 from public.scoutly_usage_events
    where user_uid = p_user_uid and feature = 'business_unlock' and resource_id = p_business_id
  ) into v_exists;

  v_status := public.scoutly_credit_status(p_user_uid);
  v_plan := v_status->>'plan';

  if v_exists then
    return v_status || jsonb_build_object('allowed', true, 'charged', false, 'alreadyUnlocked', true);
  end if;

  if v_plan in ('pro','agency','trial') then
    v_allowed := true;
  elsif v_plan = 'go' then
    v_allowed := coalesce((v_status->>'monthlyRemaining')::int, 0) > 0;
  else
    v_allowed := coalesce((v_status->>'dailyRemaining')::int, 0) > 0
      and coalesce((v_status->>'monthlyRemaining')::int, 0) > 0;
  end if;

  if not v_allowed then
    return v_status || jsonb_build_object('allowed', false, 'charged', false, 'alreadyUnlocked', false,
      'code', case when v_plan = 'free' and coalesce((v_status->>'dailyRemaining')::int,0) <= 0 then 'DAILY_CREDIT_LIMIT' else 'MONTHLY_CREDIT_LIMIT' end);
  end if;

  insert into public.scoutly_usage_events(user_uid, feature, resource_id, plan)
  values (p_user_uid, 'business_unlock', p_business_id, v_plan)
  on conflict do nothing;

  v_status := public.scoutly_credit_status(p_user_uid);
  return v_status || jsonb_build_object('allowed', true, 'charged', v_plan in ('free','go'), 'alreadyUnlocked', false);
end;
$$;

create or replace function public.scoutly_consume_ai_conversation(p_user_uid text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status jsonb;
  v_plan text;
begin
  if coalesce(trim(p_user_uid),'') = '' then raise exception 'invalid ai request'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_user_uid, 7720));
  v_status := public.scoutly_credit_status(p_user_uid);
  v_plan := v_status->>'plan';

  if v_plan = 'free' then
    return v_status || jsonb_build_object('allowed', false, 'code', 'AI_UPGRADE_REQUIRED');
  end if;

  if v_plan = 'go' and coalesce((v_status->>'aiDailyRemaining')::int,0) <= 0 then
    return v_status || jsonb_build_object('allowed', false, 'code', 'AI_DAILY_LIMIT');
  end if;

  if v_plan not in ('go','pro','agency','trial') then
    return v_status || jsonb_build_object('allowed', false, 'code', 'AI_UPGRADE_REQUIRED');
  end if;

  insert into public.scoutly_usage_events(user_uid, feature, resource_id, plan)
  values (p_user_uid, 'ai_conversation', concat(extract(epoch from clock_timestamp()), '-', random()), v_plan);

  v_status := public.scoutly_credit_status(p_user_uid);
  return v_status || jsonb_build_object('allowed', true);
end;
$$;

revoke all on function public.scoutly_effective_plan(text) from public, anon, authenticated;
revoke all on function public.scoutly_credit_status(text) from public, anon, authenticated;
revoke all on function public.scoutly_consume_business_credit(text,text) from public, anon, authenticated;
revoke all on function public.scoutly_consume_ai_conversation(text) from public, anon, authenticated;
grant execute on function public.scoutly_effective_plan(text) to service_role;
grant execute on function public.scoutly_credit_status(text) to service_role;
grant execute on function public.scoutly_consume_business_credit(text,text) to service_role;
grant execute on function public.scoutly_consume_ai_conversation(text) to service_role;
